from rest_framework import serializers

class QuerySerializer(serializers.Serializer):
    """
    Serializer for the incoming user query.
    """
    query = serializers.CharField(
        min_length=5,  # Minimum length for a meaningful query
        max_length=150, # Maximum length to prevent overly long queries
        help_text="The question to ask the RAG pipeline."
    )

class DocumentMetadataSerializer(serializers.Serializer):
    """
    Serializer for the metadata of a retrieved document.
    """
    id = serializers.CharField(max_length=255)
    score = serializers.FloatField()

class RAGResponseSerializer(serializers.Serializer):
    """
    Serializer for the RAG pipeline's response.
    """
    answer = serializers.CharField(help_text="The answer generated by the LLM.")
    retrieved_documents = DocumentMetadataSerializer(many=True, help_text="List of retrieved document metadata.")
    full_document_contents = serializers.ListField(child=serializers.CharField(), required=False)
