# Generated by Django 5.2.4 on 2025-07-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessagehistory',
            name='embedding',
            field=models.CharField(default='e5', max_length=50),
        ),
    ]
