# Generated by Django 5.2.4 on 2025-07-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_api', '0002_chatmessagehistory_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessagehistory',
            name='retrieved_documents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessagehistory',
            name='structured_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
